name: Actualisation Newsletter

on:
  schedule:
    - cron: '0 20 * * *' # Tourne tous les jours à 20h
  workflow_dispatch: # Permet de le lancer à la main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installation des bibliothèques
        run: |
          python -m pip install --upgrade pip
          pip install google-genai 

      - name: Exécution du Robot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python process.py

      - name: Sauvegarde des résultats
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Mise à jour automatique des quiz" || exit 0
          git push
