name: Update Quiz
on:
  schedule:
    - cron: '0 * * * *' # Tourne toutes les heures automatiquement
  workflow_dispatch:      # Permet de le lancer Ã  la main quand tu veux

jobs:
  build:
    runs-on: ubuntu-latest
    # On donne les permissions d'Ã©criture pour que le bot puisse enregistrer les quiz
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install google-genai

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python process.py

      - name: Save changes to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          # On ajoute le manifest et tout le contenu du dossier data
          git add manifest.json data/*.json
          # On commit seulement s'il y a des changements
          git commit -m "ðŸš€ Nouveau Quiz ajoutÃ©" || echo "Pas de nouveaux quiz Ã  enregistrer"
          git push
